sudo: false

language: generic

services:
  - docker

before_install:
  - docker --version

install:
  - docker pull rgomes/scalanative:1.0-M1

script:
  - pwd
  - ls -al
  - >
    docker run \
      -v $(pwd):/root/scala-bindgen \
      -v $HOME/.sbt:/root/.sbt \
      -v $HOME/.ivy2:/root/.ivy2 \
      -t rgomes/scalanative:1.0-M1 /bin/bash -c \
         " cd /root/scala-bindgen; \
           ln -s /usr/bin/llvm-config-3.8 /usr/bin/llvm-config; \
           sbt clean tests/test"

before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
  - rm -rf $HOME/.ivy2/{cache,local}/org.scala-native/

cache:
  directories:
    - $HOME/.coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c72c4bf49919f4844030
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
