sudo: false

language: generic

services:
  - docker

before_install:
  - docker --version

install:
  - docker pull rgomes/scalanative:1.0-M1

script:
  - pwd
  - ls -al
  - >
    docker run \
      -v $(pwd):/root/scala-bindgen \
      -v $HOME/.sbt:/root/.sbt \
      -v $HOME/.ivy2:/root/.ivy2 \
      -t rgomes/scalanative:1.0-M1 /bin/bash -c \
         " cd /root; \
           rm -r -f ~/.ivy2/cache/com.lihaoyi/ ~/.ivy2/local/com.lihaoyi/; \
           git clone https://github.com/lihaoyi/utest; \
           pushd utest; \
           sbt clean +publishLocal; \
           popd; \
           wget -O /tmp/utest_native0.3_2.11.jar https://www.dropbox.com/sh/bb3p4grafp0027a/AAB7-L1d6fkNmVPVVajua5vRa/utest_native0.3_2.11.jar; \
           cd /root/scala-bindgen; \
           bin/scalafmt --test; \
           bin/clangfmt --test; \
           sbt clean bindgen/test tests/test"

before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
  - rm -rf $HOME/.ivy2/{cache,local}/org.scala-native/

cache:
  directories:
    - $HOME/.coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c72c4bf49919f4844030
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
